### ISSUE TITLE
Can't access any document from the Drive while using a "http" instance

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-googleapps#16]
Steps to reproduce:

1. Configure the Google Apps Integration (Pro) https://store.xwiki.com/xwiki/bin/view/Extension/GoogleAppsIntegration#installation on a local XWiki instance eg. http://apps.xwiki.com:8080/xwiki/bin/view/Main/
2. Log in with Google
3. Access the Google Apps Integration page eg. http://apps.xwiki.com:8080/xwiki/bin/view/GoogleApps/
4. Click on the "TestDocumentList" link
5. Access one of the documents
6. Go back to http://apps.xwiki.com:8080/xwiki/bin/view/GoogleApps/
7. Click on the "DriveMacroTest" link
8. Search for a document from the drive
9. Access it

Expected results: The user can connect and access documents from the Google Drive.

Actual results: The user can connect, can see the listed documents from the Drive but can't access them.

**NOTE**: I've noticed on the Credentials page (https://console.developers.google.com/apis/credentials/) while looking at the Scopes for Google APIs that some Api's that were required in documentation are not available because they require "https"
![GoogleAPI](https://user-images.githubusercontent.com/40691112/55167573-ee27f700-5179-11e9-8f5a-e762bc899e03.jpg)

Environment: Windows 10, XWiki 8.4 and 10.8.3 Standard with Chrome 73

![ResultDriveMacroTest](https://user-images.githubusercontent.com/40691112/55167594-f718c880-5179-11e9-969d-dd58cdedb7c6.jpg)
![ClickingOnDriveMacroTest](https://user-images.githubusercontent.com/40691112/55167596-f718c880-5179-11e9-88f4-27718b76fdaf.jpg)
![ResultClickOnDocumentFromDocumentList](https://user-images.githubusercontent.com/40691112/55167598-f7b15f00-5179-11e9-8878-2b40244a7d62.jpg)

**Comment by polx** [comment]
This is a documentation issue: We should always require https if the drive integration is required.
Under some hackish circumstances, you can make some of the configuration without it, but, as you read in the documentation, it is required for the drive access.
I've made a first attempt to clear the documentation.

**Comment by polx** [comment]
This is a documentation issue: We should always require https if the drive integration is required.
Under some hackish circumstances, you can make some of the configuration without it, but, as you read in the documentation, it is required for the drive access.
I've made a first attempt to clear the documentation. Please comment.
Paul

**Comment by polx** [comment]
I have modified the documentation to this effect.
