### ISSUE TITLE
Warn if the authenticator is not configured

### ISSUE THREAD

**Issue by polx** [xwikisas/application-googleapps#19]
The installation instructions indicate that xwiki.cfg be enriched with two lines.
This is the only part of the installation instructions which is not completely self-explanatory. It is thus suggested to add a warning into the configuration-sheet, so that an administrator is warned that the configuration is missing.

**Comment by polx** [comment]
This commit (84c646f) provides the necessary function but only works for xwiki version 11 onwards.

**Comment by polx** [comment]
As it should like:
<img width="804" alt="Screenshot 2019-06-21 at 11 25 42" src="https://user-images.githubusercontent.com/818835/59912968-84855500-9417-11e9-858d-92993796d3a3.png">

**Comment by ane-gabriela** [comment]
I've tested on 8.4.5, 10.11.8 and 11.5RC1 with Chrome 75. I don't see the message from above anywhere. 

I get the same on all of them:

- https://up1.xwikisas.com/#YC_XKkKpngOX_NSaJYtrIA

- https://up1.xwikisas.com/#shCQL3dQW8KuSWRtj13MyA

- https://up1.xwikisas.com/#Hqm9xDQIhkRiUTk43TVrSw

Followed the steps from https://store.xwiki.com/xwiki/bin/view/Extension/GoogleAppsIntegration#installation

**Comment by polx** [comment]
Ok. I've been bitten by the uncertainty of prog-rights and, it seems, xar-importing (&lt; in the xar became \< in the page content which yielded something that was not a comment anymore).

**Comment by polx** [comment]
Solved in 2.4-rc-9.
