### ISSUE TITLE
Buttons with FR language aren't appearing corectly

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-googleapps#23]
The text on FR language isn't centered properly in the buttons.

![8 4 5 Buttons FR](https://user-images.githubusercontent.com/40691112/60603616-c53d8080-9dbe-11e9-9a41-de98e907300f.jpg)
![10 11 8 Buttons FR](https://user-images.githubusercontent.com/40691112/60603618-c5d61700-9dbe-11e9-8055-70cb721701aa.jpg)
![11 5Buttons](https://user-images.githubusercontent.com/40691112/60603619-c5d61700-9dbe-11e9-9ec2-1251b6d1e032.jpg)

**Comment by polx** [comment]
Fixed.
<img width="643" alt="Screenshot 2020-11-25 at 07 55 38" src="https://user-images.githubusercontent.com/818835/100193252-b1367980-2ef3-11eb-9cd0-b8e6072de4bd.png">
<img width="642" alt="Screenshot 2020-11-25 at 07 55 26" src="https://user-images.githubusercontent.com/818835/100193253-b267a680-2ef3-11eb-9c6f-3382e76b4c95.png">

**Comment by polx** [comment]
2.4.8-RC1 is released with this fixed.
I pull it with [this URL](http://127.0.0.1:8080/xwiki/bin/admin/XWiki/XWikiPreferences?section=XWiki.Extensions&extensionId=com.xwiki.googleapps%3Aapplication-googleapps&extensionVersion=2.4.8-RC1).
