### ISSUE TITLE
Legacy People API needs to be activated

### ISSUE THREAD

**Issue by oanat** [xwikisas/application-googleapps#33]
Steps to reproduce:
* download XWiki 11.9
* install and configure Google Apps v2.4.1 (enable all requested APIs Google+ API, Google Drive API)
* click on the Google login button

**Result**: velocity error regarding the missing People API even after the API has been enabled

<img width="843" alt="PeopleAPIError" src="https://user-images.githubusercontent.com/370535/67951215-c14a2f80-fbf3-11e9-99b6-fa8d0328214c.png">

**Expected result:** the user is logged in and the profile is created without any error

**Comment by polx** [comment]
Why 2.4.1 and not 2.4.2 ?
(I don't think it makes a difference).

I've just tested it with xwiki 11.8.1 with the APIs and indeed have the "Legacy People API" (private) activated by me. It seems that my account has this API activated as a result of update on the side of Google.

So I'll reformulate this issue as a documentation update.

It does not feel good to request to use a legacy API.

@oanat: can you please try to activate this API and test again in your settings?

**Comment by polx** [comment]
I've been trying with another project and activated the Google+, Drive, and People API and got the same error. While activating the APIs, I could not find the legacy API by a search method. This means that it is not something we can advise in the installation manual.

The help message indicates that the URL https://console.developers.google.com/apis/api/legacypeople.googleapis.com/overview?project=xxx should be used. However that URL gives an error at Google. I've sent a feedback...

**Comment by polx** [comment]
So it seems that the legacy warning is bad one: no new installation will succeed.

The description is here: https://developers.google.com/people/legacy and it explains that this is a layer of compatibility that has been automatically activated for _developers_ that already had activated the Google+ API. The good news: existing installations of an XWiki which have been _somewhat active_ (based on traffic, no numbers mentioned) with the login function of the GoogleApps application will not break.

That page also states that: _Note that you can't manually enable the Legacy People API for any new developer projects._: In this parlance (Web cloud APIs) a developer is a website, so any new XWiki installation is a new developer and will not be able to activate the legacy API necessay to run the GoogleApps application's login (and thus drive) functionality. 

The recommendation is that the _developers_ (so: First we, then the XWiki's administrators) should upgrade to new APIs such as the [Google People API](https://developers.google.com/people/).

Thanks very much @oanat  to have spotted that!
The bug remains a blocker.

**Comment by oanat** [comment]
> Why 2.4.1 and not 2.4.2 ?
> (I don't think it makes a difference).
> 
> I've just tested it with xwiki 11.8.1 with the APIs and indeed have the "Legacy People API" (private) activated by me. It seems that my account has this API activated as a result of update on the side of Google.
> 
> So I'll reformulate this issue as a documentation update.
> 
> It does not feel good to request to use a legacy API.
> 
> @oanat: can you please try to activate this API and test again in your settings?

As mentioned in the description, even after I tried to activate the API it still did not work.

**Comment by polx** [comment]
Hold on. Was it possible to activate it for you?
(was it listed on the bottom of the Dashboard under the APIs list with a private note like by me)
The error message says that the API is not activated.

**Comment by oanat** [comment]
Yes, I wad able to search inside the Library and enable it. But the error persists like the action did not propagate: <img width="726" alt="PeopleAPIEnabled" src="https://user-images.githubusercontent.com/370535/68015172-46881f80-fc9a-11e9-85ea-eac4e7c3dc63.png">

**Comment by polx** [comment]
A first working java version is in this branch https://github.com/polx/application-googleapps/tree/peopleAPImigrate
I'll be focussing to xwiki 9.

**Comment by polx** [comment]
PS: @oanat : that API (in the picture) is that of the new People API and not the legacy one. This is where we are migrating to.

**Comment by polx** [comment]
Thank you @oanat, this is now fixed in [version 2.4.3](https://github.com/xwikisas/application-googleapps/releases/tag/application-googleapps-2.4.3).

I'll note that testing should be done from an account that has never had the legacy API of Google+ API activated. It is not enough to test it from an account that had it once working but create a new project.

**Comment by oanat** [comment]
@polx I confirm the error was fixed on my side after the upgrade to v2.4.3.

**Comment by ane-gabriela** [comment]
I have a case where I had the API's enabled but I didn't have much traffic which resulted in the log in with Google not being possible anymore.

![ErrorLogIn](https://user-images.githubusercontent.com/40691112/68287573-99434c00-008b-11ea-843f-423631e0ee4b.jpg)

This is something to mention in case there are clients that are also in this situation. The solution is the 2 steps process:

1. Enable Google People API
2. Upgrade to Google Apps Integration (Pro) 2.4.3

**Comment by polx** [comment]
I thus recommend to proceed as follows:

* Adjust the installation instructions so that the People API is recommended and not anymore the Plus API
* Inform any license owner by email that they may be forced to update the GoogleApps application to the version 2.3.4 and that we recommend that they do so ASAP. An update is done in two steps: activate the [People API](https://console.developers.google.com/apis/library/people.googleapis.com) and request an upgrade of the GoogleApps application within the XWiki administration. Wiki administrators and users will recognize that they are forced to update if an error from Google indicating that the Legacy People API needs to be activated is presented; attempts to activate the legacy API will not work as documented in the [documentation](https://developers.google.com/people/legacy).

thanks
Pauls
