### ISSUE TITLE
Restrict domain for users to login doesn't work

### ISSUE THREAD

**Issue by CamiAndrei** [xwikisas/application-googleapps#37]
Steps to reproduce:
* Installed v2.4.3. 
* Configured application
Results:
* The application works fine without restricting the domain
* When adding a domain in " XWiki Login Behaviour" in XWiki configuration, the authentication fails with the following message :
![Screenshot from 2019-12-02 10-53-01](https://user-images.githubusercontent.com/12369283/69945340-08c52380-14f2-11ea-820a-8c1521435005.png)

**Comment by polx** [comment]
A release candidate is done, version 2.4.4-RC1 . 
Please test it by using the advanced search with the following parameters:
* extension Id: com.xwiki.googleapps:application-googleapps
* version: 2.4.4-RC1

If successful, we shall release 2.4.4 based on that.
