### ISSUE TITLE
GoogleApps breaks if getURL results to absolute URLs

### ISSUE THREAD

**Issue by polx** [xwikisas/application-googleapps#43]
If one manages to have absolute URLs returned by the getURL methods, then GoogleApps settings breaks with a syntax error.

**Comment by polx** [comment]
<img width="632" alt="Screenshot 2020-03-31 at 23 23 47" src="https://user-images.githubusercontent.com/818835/78076432-aea47400-73a6-11ea-9cf1-cb325ec2a799.png">
As experienced.

**Comment by CamiAndrei** [comment]
This issue can be caused by a custom set up of URLs, like short URLs. With the fix added in this ticket the application works again with absolute URLs setup too.
