### ISSUE TITLE
Authentification fails when photo has a name too long

### ISSUE THREAD

**Issue by CamiAndrei** [xwikisas/application-googleapps#58]
Steps to reproduce:
* Login with a google user ( make sure it has an attachment that it is fetched that has a longer name than 255 characters)
Expected results:
* The user is created
* The login works
Actual result:
* The user is created
* The login fails with:
`Erreur : Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'XWA_FILENAME' at row 1`
![image](https://user-images.githubusercontent.com/12369283/100125248-3afb2e00-2e85-11eb-8aa1-fc01519bd3e9.png)

Maybe we should just ignore the image, even if could not be saved in the database the attachment could not be saved or even a rename, if that's possible.

Current workaround:  Disable "User image" from the Google Apps Administration.

**Comment by polx** [comment]
It would be just as complex to just trim the filename...

**Comment by polx** [comment]
Fixed by trimming the filename when it is imported.
