### ISSUE TITLE
Broken link on the GoogleApps homepage

### ISSUE THREAD

**Issue by oanat** [xwikisas/application-googleapps#6]
When accessing the app homepage the link "Google Apps section of the XWiki Preferences" is broken.
<img width="862" alt="brokenlink" src="https://user-images.githubusercontent.com/370535/46458846-cd30ab80-c7bf-11e8-882c-3b03b24f4add.png">

Tested with XWiki Demo Flavour 10.8 and Google Apps 2.3.3.

**Comment by acotiuga** [comment]
Fixed in https://github.com/xwikisas/application-googleapps/issues/9 (duplicated issue, by mistake.)
