### ISSUE TITLE
XWiki "Login with Google" doesn't work 

### ISSUE THREAD

**Issue by AlexandraSiriciuc** [xwikisas/application-googleapps#60]
**Steps to reproduce:**

- Installed Versions: XWiki: 13.3 & Google Apps Integration (Pro): 2.4.9
- Follow the setup instructions from https://store.xwiki.com/xwiki/bin/view/Extension/GoogleAppsIntegration#installation 
- Try to log in using Google 

**Expected result:**
The app is configured properly and the Google user can login.

**Actual result:**
Able to see "Login with Google" in the login page. When clicked "Login with Google" received the following error :
![xwiki13 3](https://user-images.githubusercontent.com/82156408/117405848-ee784c00-af14-11eb-89b3-46690880ee85.png)
![screenshot](https://user-images.githubusercontent.com/82156408/117407079-afe39100-af16-11eb-82b0-d27e8828409f.png)

**Comment by polx** [comment]
Is there a domain-name restriction in the GoogleApps admin?

**Comment by AlexandraSiriciuc** [comment]
No, there is no domain-name restriction, please see the screenshot:
![googleapps-admin](https://user-images.githubusercontent.com/82156408/117444389-14681580-af42-11eb-9f74-f93915e52bb0.png)

**Comment by polx** [comment]
Maybe a whitespace inside the field?
The code indeed only checks if the field is completely empty. Any non-printable character would still count.

**Comment by AlexandraSiriciuc** [comment]
I checked to make sure there was no whitespace, setup saved and after restarting the instance, the same error.

**Comment by polx** [comment]
Is the site accessible for me to get into? What you describe is exactly contrary to what I read in the code and what I tested.
E.g. what does /xwiki/bin/edit/GoogleApps/GoogleAppsConfig?editor=object&force=1  show?
paul

**Comment by ppantiru** [comment]
This was tested on local 13.3 instances and the result was the same for me and Ilie as well.
We followed the instructions from the store page, so either the instructions are not up to date anymore or there has been a regression of sorts.
However I have not tested for earlier versions.

**Comment by AlexandraSiriciuc** [comment]
Please find below a screenshot from the mentioned page: 
![Objectscreenshot](https://user-images.githubusercontent.com/82156408/117464109-0671bf00-af59-11eb-9a55-0a4ad45e0573.png)

Thanks, please let me know if there is anything I can do

**Comment by polx** [comment]
Thank you @AlexandraSiriciuc . This is solved in 2.4.10.
