### ISSUE TITLE
Google Apps Pro, weird redirect behavior

### ISSUE THREAD

**Issue by chris968** [xwikisas/application-googleapps#61]
We using the plugin for years now and we have strange redirection behavior since the beginning.
First it result in a error after a successful login so people had to reload the root page of the wiki, then we activated encoded slash in Tomcat and then we was now redirected to a page that don't exist.

Here is the redirection which is applied right after a successful login:

https://xwiki.ourcompany.com/xwiki/bin/view/GoogleApps/Login??srid=XXXXXXXX&xredirect=%2Fxwiki%2Fbin%2Fview%2FMain%2F%3Fsrid%XXXXXXXX

**Comment by AndreeaChi** [comment]
Hi! @chris968 , does this redirect behavior still happen with the latest Google Apps Integration Pro 2.5.2 version?

**Comment by chris968** [comment]
Hi @AndreeaChi , sorry to no have reported that I solved the issue on our side in a first place, I had to proxy pass the `/xwiki`path instead of `/`on our front-end reverse proxy, everything working since.
