### ISSUE TITLE
Can't embed multiple documents in one page

### ISSUE THREAD

**Issue by CamiAndrei** [xwikisas/application-googleapps#62]
Steps to reproduce:
* add in a page 2 drive macro:

{{drive/}} 

{{drive/}} 

* Save the page
* Add documents in both search bars
* Click Search 

Expected results:
* Only the first google search input returns a result.
 
Actual results: 
* Both google search inputs bring the same result, that will be displayed.

The current workaround would be to use different pages to embed documents, then use [XWiki Display Macro](https://extensions.xwiki.org/xwiki/bin/view/Extension/Display%20Macro)  in the page where you want multiple documents to be embedded.

**Comment by trrenty** [comment]
To successfully embed two drive documents into one page, we need to assign a separate number to each macro as such:
```
{{drive nb="1"}}{{/drive}}

{{drive nb="2"}}{{/drive}}
```
Searching for a document will now return a result only for the input we sent 
![image](https://user-images.githubusercontent.com/45433221/164413357-3b1a5b34-ae8d-46a0-9470-f6395c967fb2.png)

After also setting a custom height to the macros
```
{{drive nb="4" height="200px"}}{{/drive}}

{{drive nb="5" height="200px"}}{{/drive}}
```
and assigning a document to the second macro, I have the following result:

![image](https://user-images.githubusercontent.com/45433221/164413818-e8704220-c464-46aa-b527-89ba115f68e3.png)
